CREATE DATABASE ecommerce;

CREATE TABLE ecommerce.supplier (
  SUPP_ID INT NOT NULL,
  SUPP_NAME VARCHAR(50) NOT NULL,
  SUPP_CITY VARCHAR(50) NOT NULL,
  SUPP_PHONE VARCHAR(50) NOT NULL,
  PRIMARY KEY (SUPP_ID));
  
  CREATE TABLE ecommerce.cutomers (
  CUS_ID INT NOT NULL,
  CUS_NAME VARCHAR(50) NOT NULL,
  CUS_PHONE VARCHAR(10) NOT NULL,
  CUS_CITY VARCHAR(30) NOT NULL,
  CUS_GENDER CHAR(12) NOT NULL,
  PRIMARY KEY (CUS_ID));
  
  CREATE TABLE ecommerce.category (
  CAT_ID INT NOT NULL,
  CAT_NAME VARCHAR(20) NOT NULL,
  PRIMARY KEY (CAT_ID));

  CREATE TABLE ecommerce.product(
  PRO_ID INT NOT NULL,
  PRO_NAME VARCHAR(20) NULL,
  PRO_DESC VARCHAR(60) NULL,
  CAT_ID INT NULL,
  PRIMARY KEY (PRO_ID),
  CONSTRAINT CAT_ID
    FOREIGN KEY (CAT_ID)
    REFERENCES ecommerce.category (CAT_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE);
    
CREATE TABLE ecommerce.supplier_pricing (
  PRICING_ID INT NOT NULL,
  PRO_ID INT NOT NULL,
  SUPP_ID INT NOT NULL,
  SUPP_PRICE INT NOT NULL,
  PRIMARY KEY (PRICING_ID),
  CONSTRAINT PRO_ID
    FOREIGN KEY (PRO_ID)
    REFERENCES ecommerce.product (PRO_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT SUPP_ID
    FOREIGN KEY (SUPP_ID)
    REFERENCES ecommerce.supplier (SUPP_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE);
    
CREATE TABLE ecommerce.order (
  ORD_ID INT NOT NULL,
  ORD_AMOUNT INT NULL,
  ORD_DATE DATE NULL,
  CUS_ID INT NULL,
  PRICING_ID INT NULL,
  PRIMARY KEY (ORD_ID),
  CONSTRAINT CUS_ID
    FOREIGN KEY (CUS_ID)
    REFERENCES ecommerce.cutomers (CUS_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT PRICING_ID
    FOREIGN KEY (PRICING_ID)
    REFERENCES ecommerce.supplier_pricing (PRICING_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE TABLE ecommerce.rating (
  RAT_ID INT NOT NULL,
  ORD_ID INT NOT NULL,
  RAT_RATSTARS INT NOT NULL,
  PRIMARY KEY (RAT_ID),
  CONSTRAINT ORD_ID
    FOREIGN KEY (ORD_ID)
    REFERENCES ecommerce.order (ORD_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE);
    
    
    
    
    
    
    
    
    
    
    
  
